---
title: "Storm Damage Report"
author: "Hal Peterson"
date: "January 24, 2015"
output: html_document
---

# Synopsis



# Data Processing

## Load data set

```{r cache=TRUE}
storms <- read.csv ('StormData.csv.bz2')
```

Convert damage exponents to numeric values.

```{r}
allExponents <- union (levels (storms$CROPDMGEXP),
                       levels (storms$PROPDMGEXP))
numex <- as.numeric (allExponents)
numex[allExponents %in% c('h', 'H')] <- 2
numex[allExponents %in% c('k', 'K')] <- 3
numex[allExponents %in% c('m', 'M')] <- 6
numex[allExponents %in% c('b', 'B')] <- 9
numex[allExponents %in% c('', '?', '-', '+')] <- 0
stopifnot (! any (is.na (numex)))
numex <- 10 ^ numex
numex
```


Categories gleaned from NOAA, plus some tools for cleaning the raw data:

```{r}
stormTypes <- c ('Astronomical Low Tide',
                 'Avalanche',
                 'Blizzard',
                 'Coastal Flood',
                 'Cold/Wind Chill',
                 'Debris Flow',
                 'Dense Fog',
                 'Dense Smoke',
                 'Drought',
                 'Dust Devil',
                 'Dust Storm',
                 'Excessive Heat',
                 'Extreme Cold/Wind Chill',
                 'Flash Flood',
                 'Flood',
                 'Freezing Fog',
                 'Frost/Freeze',
                 'Funnel Cloud',
                 'Hail',
                 'Heat',
                 'Heavy Rain',
                 'Heavy Snow',
                 'High Surf',
                 'High Wind',
                 'Hurricane/Typhoon',
                 'Ice Storm',
                 'Lakeshore Flood',
                 'Lake-Effect Snow',
                 'Lightning',
                 'Marine Hail',
                 'Marine High Wind',
                 'Marine Strong Wind',
                 'Marine Thunderstorm Wind',
                 'Rip Current',
                 'Seiche',
                 'Sleet',
                 'Storm Tide',
                 'Strong Wind',
                 'Thunderstorm Wind',
                 'Tornado',
                 'Tropical Depression',
                 'Tropical Storm',
                 'Tsunami',
                 'Volcanic Ash',
                 'Waterspout',
                 'Wildfire',
                 'Winter Storm',
                 'Winter Weather' )

```

Of the 37 variables, not all are relevant to the analysis at hand.


# Results
